#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                /usr/bin/mv "$file" ~/.trash ;;
                # /usr/bin/mv -vf "$@" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        esac
done
