#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.trash ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-b")
                wal -i "$file" ;;
        esac
done
