#!/bin/python
import re
import sys
import urllib.request
from bs4 import BeautifulSoup

def get_lyrics():
    artist = sys.argv[1]
    artist = artist.lower()
    # print (artist)

    song_title = sys.argv[2]
    song_title = song_title.lower()
    # print (song_title)

    # remove all except alphanumeric characters from artist and song_title
    artist = re.sub('[^A-Za-z0-9]+', "", artist)
    song_title = re.sub('[^A-Za-z0-9]+', "", song_title)
    if artist.startswith("the"):    # remove starting 'the' from artist e.g. the who -> who
        artist = artist[3:]
    url = "http://azlyrics.com/lyrics/"+artist+"/"+song_title+".html"
    
    try:
        content = urllib.request.urlopen(url).read()
        soup = BeautifulSoup(content, 'html.parser')
        lyrics = str(soup)
        # lyrics lies between up_partition and down_partition
        up_partition = '<!-- Usage of azlyrics.com content by any third-party lyrics provider is prohibited by our licensing agreement. Sorry about that. -->'
        down_partition = '<!-- MxM banner -->'
        lyrics = lyrics.split(up_partition)[1]
        lyrics = lyrics.split(down_partition)[0]
        lyrics = lyrics.replace('<br>','').replace('</br>','').replace('</div>','').strip()
        return lyrics
    except Exception as e:
        return "Exception occurred \n" +str(e)

if len(sys.argv) != 3:
    print ("Error: Artist name and Song name required")
    print ('Example: lyricsArgv "Post Malone" "Sunflower"')
else:
    print(get_lyrics())


